<?php

namespace App\Models;

use Carbon\Carbon;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Device extends Model
{
	use HasFactory;

	protected $table = 'devices';

    protected $fillable = [
        'device_name',
        'serial_number',
        'model',
        'firmware_version',
        'status',
    ];

    /**
     * Use serial_number for route model binding
     */
    public function getRouteKeyName()
    {
        return 'serial_number';
    }

    /**
     * Users paired with this device (MULTI-USER)
     */
    public function users()
    {
        return $this->belongsToMany(User::class, 'device_users', 'device_id', 'user_id');
    }

    /**
     * Notifications generated by this device
     */
    public function notifications()
    {
        return $this->hasMany(Notification::class);
    }

    public function sensors()
    {
        return $this->hasMany(Sensor::class);
    }

    public function treatment_reports()
    {
        return $this->hasMany(TreatmentReport::class);
    }
}
